spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb?createDatabaseIfNotExist=true
    username: root
    password: 12345678 
  jpa:
    hibernate:
      naming:
        physical-stratergy: org.hibernate.model.naming.PhysicalNamingStandardImpl
